FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /app

RUN git config --global --add safe.directory /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -v -o webserver -ldflags '-extldflags "-static"' -buildvcs=false .

#runtime
FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/webserver .

EXPOSE 8082

CMD ["./webserver"]